### ISSUE TITLE
wiki documentation uses original group id

### ISSUE THREAD

**Issue by chris-renner** [mavenplugins/unleash-maven-plugin#10]
e.g. in https://github.com/mavenplugins/unleash-maven-plugin/wiki/unleash%3Aperform

Full Name
com.itemis.maven.plugins:unleash-maven-plugin:1.0.0:perform

**Comment by mhoffrog** [comment]
@chris-renner Many thanks for notifying this! Wiki content has been updated accordingly. All Wiki pages passed and updated as far as applicable. Please have a look and let us know if their is any more finding or this issue can be closed.

**Comment by chris-renner** [comment]
thanks, for this quick fix.
issue can be closed
